name: Unit Test
on: ["push"]
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Setup Go
        uses: action/setup-go@v2
        with:
          go-version: 1.18
      - name: Run UnitTest
        run: |
          go test ./... -count 1
